// src/react/view/compress/components/FileItems.tsx
import { DeleteOutlined, FileTextOutlined, FolderOutlined } from '@ant-design/icons';
import type { TableProps } from 'antd';
import { Button, Popconfirm, Spin, Table } from 'antd';
import { useEffect, useRef, useState } from 'react';
import { handler } from '../../../util/vscode';
import { FileInfo } from '../zipTypes';

const columns: TableProps<FileInfo>['columns'] = [
    {
        title: 'Name',
        dataIndex: 'name',
        width: 300,
        onCell: (entry) => ({ onClick: () => handler.emit('openPath', entry) }),
        render: (text, entry) => <>
            {entry.isDirectory ? <FolderOutlined /> : <FileTextOutlined />}
            {text}
        </>,
    },
    { title: 'Modified', dataIndex: 'modifyDateTime', width: 190, onCell: (entry) => ({ onClick: () => handler.emit('openPath', entry) }) },
    { title: 'Compressed', dataIndex: 'compressedSize', width: 120 },
    { title: 'Origin', dataIndex: 'fileSize', width: 80 },
    {
        title: 'Action',
        key: 'action',
        width: 60,
        render: (_, entry) => (
            <>
                {/* 需要上色 */}
                <Popconfirm
                    title="Delete the file"
                    description="Are you sure to delete this file?"
                    onConfirm={() => {
                        handler.emit('removeFile', entry.entryName)
                    }}
                    okText="Yes"
                    cancelText="No"
                >

                    <Button type="primary" danger>
                        <DeleteOutlined />
                    </Button>
                </Popconfirm>
            </>
        ),
    }
];

export default function FileItems({ items }) {
    const [height, setHeight] = useState(window.innerHeight - 100)
    const loading = useRef(null)
    loading.current = loading.current == null
    useEffect(() => {
        window.addEventListener('resize', () => {
            setHeight(window.innerHeight - 100)
        })
    }, [])
    return (
        <Spin spinning={loading.current}>
            <Table columns={columns} rowKey="entryName" dataSource={items}
                style={{ height, overflow: 'auto' }} pagination={false} expandable={{ showExpandColumn: false }}
            />
        </Spin>
    )
}

// packages/zip-viewer/src/components/zip/FileItems.vue
<template>
  <!--    https://element-plus.org/zh-CN/component/table.html  -->
    <el-table :data="data" style="width: 100%" @row-click="clickRow" :max-height="remainHeight">
        <el-table-column label="Name" width="350">
            <template #default="scope">
                <FileItem :info="scope.row"/>
            </template>
        </el-table-column>
        <el-table-column prop="modifyDateTime" label="Modified" width="190"/>
        <el-table-column prop="compressedSize" label="Compressed" width="105"/>
        <el-table-column prop="fileSize" label="Origin" width="80"/>
        <el-table-column label="Action" width="80">
            <template #default="scope">
                <el-popconfirm width="220" confirm-button-text="OK" cancel-button-text="Cancel" :icon="InfoFilled"
                               title="Are you sure to delete this?" :hide-after="0" v-if="scope.row.name!='..'"
                               @confirm="reqDelete(scope.row)">
                    <template #reference>
                        <el-button type="danger" size="small" :icon="Delete"></el-button>
                    </template>
                </el-popconfirm>
            </template>
        </el-table-column>
    </el-table>
</template>
<script lang="ts" setup>
import FileItem from "@/components/zip/FileItem.vue";
import type {PropType} from "vue";
import {ref, watch} from "vue";
import {FileInfo} from "@/components/zip/zipTypes";
import {getVscodeEvent} from "@/vscode";
import {Delete, InfoFilled} from '@element-plus/icons-vue'
// https://element-plus.org/zh-CN/component/table.html
const props = defineProps({
    items: Object as PropType<FileInfo[]>
})
const data = ref(props.items)
const remainHeight = ref(window.innerHeight - 100)
window.onresize = () => {
    remainHeight.value = window.innerHeight - 100;
}
watch(() => props.items, (items) => {
    data.value = items
})
const updateData = (items: FileInfo[]) => {
    data.value = items
}

const vscodeEvent = getVscodeEvent()

const reqDelete = (entry: FileInfo) => {
    vscodeEvent.emit('removeFile', entry.entryName)
}

const clickRow = (entry: FileInfo, column: any) => {
    if (column.no != 0) return;
    vscodeEvent.emit('openPath', {
        isDirectory: entry.isDirectory,
        entryName: entry.entryName
    })
}

defineExpose({
    updateData
})
</script>
